# Generated by Django 5.0.1 on 2024-04-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_board_date_column_date_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='date',
        ),
        migrations.RemoveField(
            model_name='column',
            name='date',
        ),
    ]
