# Generated by Django 5.0.1 on 2024-05-07 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_board_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
